### ISSUE TITLE
Unclear license

### ISSUE THREAD

**Issue by elho** [xai/maildirdiff#1]
The `LICENSE` file contains a MIT license, but the actual code `maildirdiff.py` has the standard GPL license statement saying it is GPL v2.

This should be clarified either way.
If that GPL license statement was a copy&paste from some other project that is not your own and some code has been copied along with it, sticking with GPL v2 would be only choice, obviously.

**Comment by xai** [comment]
Thanks for noticing! I'll take a look and clear this up.

**Comment by xai** [comment]
Ok, I just verified that the code is all from me, no other project involved.
Do you have a preference regarding a license for your use case? I don't have strong feelings in this case, so I would be happy to comply with your preference.

**Comment by elho** [comment]
Well, its your code, so really up to you what you want to possibly happen or not with your work. :slightly_smiling_face: 

But as you asked, personally, I prefer GPL as I do prefer not to help or make life easy to developers of proprietary software, the downside being giving other open source projects that use some license incompatible with the GPL a hard time, too.

**Comment by xai** [comment]
Done in 26a0d24, it's GPLv2 now.

Knowing that GPL can cause some headaches in specific situations is why I asked for your preference ;)

For larger projects I make more careful choices, this one was just a quick hack to diff a set of backed-up maildirs.

As for the other issues/pr: Thank you very much -- I'll take a look later on as soon as I'm out of meetings!
